name:                dialog
version:             0.1.0.0
license:             GPL-3.0
author:              "Samuel Maginot"
maintainer:          "maginotsam@gmail.com"
copyright:           "2023 Samuel Maginot"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dialog#readme>

dependencies:
- base >= 4.7 && < 5
- process
- text
- transformers
# SDL dependencies
- sdl2
- sdl2-ttf
- sdl2-gfx
- linear

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  prompt:
    main:                Prompt.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dialog

tests:
  dialog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dialog
